name: Deploy to Firebase

on:
  push:
    branches:
      - secure-api  # Only deploy from the secure-api branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Environment File
        run: |
          mkdir -p public
          echo "window.FIREBASE_API_KEY='${{ secrets.FIREBASE_API_KEY }}';" > public/env.js
          echo "window.FIREBASE_AUTH_DOMAIN='${{ secrets.FIREBASE_AUTH_DOMAIN }}';" >> public/env.js
          echo "window.FIREBASE_DATABASE_URL='${{ secrets.FIREBASE_DATABASE_URL }}';" >> public/env.js
          echo "window.FIREBASE_PROJECT_ID='${{ secrets.FIREBASE_PROJECT_ID }}';" >> public/env.js
          echo "window.FIREBASE_STORAGE_BUCKET='${{ secrets.FIREBASE_STORAGE_BUCKET }}';" >> public/env.js
          echo "window.FIREBASE_MESSAGING_SENDER_ID='${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}';" >> public/env.js
          echo "window.FIREBASE_APP_ID='${{ secrets.FIREBASE_APP_ID}}';" >> public/env.js
          echo "window.FIREBASE_MEASUREMENT_ID='${{ secrets.FIREBASE_MEASUREMENT_ID }}';" >> public/env.js
      
 
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --project "btechbabaiii" --token "${{ secrets.FIREBASE_DEPLOY_TOKEN }}"
